name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        dependencies: ['lowest', 'highest']

    name: PHP ${{ matrix.php-version }} - ${{ matrix.dependencies }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.dependencies }}" == "lowest" ]]; then
          composer update --prefer-lowest --no-interaction --no-progress
        else
          composer install --no-interaction --no-progress
        fi

    - name: Run PHPStan
      run: composer phpstan

    - name: Run PHP CS Fixer
      run: composer cs-check

    - name: Run tests
      run: composer test

    - name: Upload coverage reports to Codecov
      if: matrix.php-version == '8.2' && matrix.dependencies == 'highest'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
